/* node tests/strings.test.js */
var assert = require('assert');
var fs = require('fs');
var vm = require('vm');
var ctx = { console: console };
vm.runInNewContext(fs.readFileSync(require('path').join(__dirname, '..', 'strings.js'), 'utf8'), ctx);
var Z = ctx.ZFStrings;
assert.strictEqual(Z.locale, 'zh');
assert.strictEqual(Z.t('urge.button'), '我现在很想');
assert.strictEqual(Z.t('urge.round', { n: 2, total: 6 }), '第 2 / 6 轮');
assert.strictEqual(Z.t('urge.streakNow', { n: 1 }), '当前连续 1 天');
assert.strictEqual(Z.t('urge.streakNow', { n: 2 }), '当前连续 2 天');
assert.strictEqual(Z.t('urge.notResisted'), '没撑住');
assert.strictEqual(Z.t('urge.count'), '已撑过');
assert.strictEqual(Z.t('urge.reasonsTitle'), '理由');
assert.strictEqual(Z.t('urge.breathTitle'), '呼吸');
assert.strictEqual(Z.t('urge.reasonsEmpty'), '还没有理由');
var streakEn = Z.table.en['urge.streakNow'];
assert.strictEqual(Z.render(streakEn, { n: 1 }, 'en'), 'Current streak: 1 day');
assert.strictEqual(Z.render(streakEn, { n: '1' }, 'en'), 'Current streak: 1 day');
assert.strictEqual(Z.render(streakEn, { n: 2 }, 'en'), 'Current streak: 2 days');
assert.strictEqual(Z.render(streakEn, { n: '1.5' }, 'en'), 'Current streak: 1.5 days');
assert.strictEqual(Z.render(streakEn, { n: 1 }, 'zh'), 'Current streak: 1 ');
assert.strictEqual(Z.table.en['urge.notResisted'], "I didn't make it this time");
assert.strictEqual(Z.table.en['urge.count'], 'Urges resisted');
assert.strictEqual(Z.table.en['urge.reasonsTitle'], 'Your reasons');
assert.strictEqual(Z.table.en['urge.breathTitle'], 'Take a breath');
assert.strictEqual(Z.table.en['urge.reasonsEmpty'], 'No reasons yet. Add one in Settings.');
assert.strictEqual(Z.table.en['urge.button'], "I'm having an urge");
assert.strictEqual(Z.table.en['urge.resisted'], 'I made it through');
assert.strictEqual(Z.table.en['stats.longest'], 'Longest streak');
assert.strictEqual(Z.table.en['stats.totalDays'], 'Total days');
assert.strictEqual(Z.t('record.save'), '保存');
assert.strictEqual(Z.t('day.timeline'), '时间线');
assert.strictEqual(Z.t('relapse.kept'), '已记录 · 天数不变');
assert.strictEqual(Z.t('time.today', { time: '15:10' }), '今天 15:10');
assert.strictEqual(Z.t('time.date', { m: 10, d: 5, time: '15:10' }), '10月5日 15:10');
assert.strictEqual(Z.table.en['record.save'], 'Save');
assert.strictEqual(Z.table.en['day.timeline'], 'Timeline');
assert.strictEqual(Z.table.en['relapse.kept'], 'Logged · Streak kept');
assert.strictEqual(Z.render(Z.table.en['time.today'], { time: '15:10' }, 'en'), 'Today 15:10');
assert.strictEqual(Z.render(Z.table.en['time.date'], { month: 'Oct', d: 5, time: '15:10' }, 'en'), 'Oct 5 15:10');
Object.keys(Z.table.zh).forEach(function (k) {
  assert.ok(Object.prototype.hasOwnProperty.call(Z.table.en, k), 'missing en ' + k);
});
['fail', 'shame', 'relapse', 'broke'].forEach(function (word) {
  Object.keys(Z.table.en).forEach(function (k) {
    assert.strictEqual(String(Z.table.en[k]).toLowerCase().indexOf(word), -1, k + ' has ' + word);
  });
});
console.log('strings tests ok');